title:             Aman's Blog
email:             aman.iitk072@gmail.com
description:       Lot's of blas
author:            Aman Abhishek Tiwari
baseurl:           ""
url:               "http://amanabt.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   amanabt
facebook_username: aman.iitk072

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
